### ISSUE TITLE
[Bug] No Ore Generation

### ISSUE THREAD

**Issue by Flainity** [EwyBoy/OreTweaker#37]
I don't want to reopen this again, but currently I have the same problem.

###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 36.2.8

###### **Mod Version**
> 2.5.1

###### **Reference Issue**
> #32 

###### **Describe the bug**
> As described in #32 , no ores underground, just stone and air.

###### **How to reproduce**
> I didn't upgrade the mod version. I just installed it today and never used it before. I tried every solution mentioned here, but without success. Neither does reinstalling work, nor deleting and regenerating the default configs.
I also removed every other mod except of World Stripper, still no ore generation.

**Comment by EwyBoy** [comment]
After some testing I have figured out older OS such as Win7 could cause this issue.
What OS are you guys currently on? @Flainity @Atlntssplayer @jankornfeld @lynnpye

**Comment by jankornfeld** [comment]
Win 10

**Comment by Flainity** [comment]
Windows 11

I also tried out your solution with a curseforge clean install, but that also didn't work.

**Comment by EwyBoy** [comment]
Hmmm, I don't think it could have anything with Java version either. Very hard for me to fix a bug only occurring for some users but not all and especially I can't seem to replicate it. I am still looking for a solution to this.

**Comment by EwyBoy** [comment]
Right now everything works perfectly fine for me using this setup:

Minecraft: `1.16.5 `
Forge:  `36.2.9`
Java:  ` 1.8.0_51 64 bit` by [Adopt OpenJDK](https://adoptopenjdk.net/) (Hotspot)
OS:  `Windows 10 Pro`
Launched through: `CurseForge App`
Other mods: World Stripper

**Comment by jankornfeld** [comment]
I added an error above from my server. This could be a good starting point. Do you know where this error is thrown (class and line of code)? @EwyBoy

**Comment by EwyBoy** [comment]
@jankornfeld yes, gonna look closer into why it does throw that error. I also think if it works for 1.17 it's either a problem with specific java 8 versions or some difference in the code between 1.16 & 1.17. Gonna compare the two different versions and see if I can find anything. Then I will test on some other Java 8 distributions and versions and see if it can have anything to do with that.

**Comment by jankornfeld** [comment]
@EwyBoy I believe that 1.17.1 is using Java 16. At least the server is only starting with that version

**Comment by EwyBoy** [comment]
@jankornfeld Yes, 1.17 changed to Java 16, so I suspect java version could be the cause of the bug.

**Comment by EwyBoy** [comment]
Feel free to update ur Java 8 to this version that is confirmed to work:
https://adoptium.net/?variant=openjdk8

**Comment by jankornfeld** [comment]
I just startet a new fresh install of a 1.17.1 server with this mod and stripper installed (newest versions from curseforge). changed coal and diamond ore to 0. And no ores in the ground and no error message in the console. And I haven't changed the java version.

Minecraft: 1.17.1
Forge: 37.0.103
Java: "16.0.2" 2021-07-20
OS: Windows 10 Pro
Launched through: CurseForge App
Other mods: World Stripper

**Comment by EwyBoy** [comment]
Just tested on a brand new 1.17.1 server with latest forge version with only world stripper and ore tweaker. Also changed coal and diamond ore to 0 like you can see below. Worked perfectly fine for me.

```json
{
  "oreConfig": [
    {
      "ore": "minecraft:coal_ore",
      "filler": "minecraft:stone",
      "minY": 1,
      "maxY": 128,
      "maxVeinSize": 16,
      "spawnRate": 0.0,
      "biomeBlacklist": [],
      "biomeWhitelist": []
    }
  ]
}
```

```json
{
  "oreConfig": [
    {
      "ore": "minecraft:diamond_ore",
      "filler": "minecraft:stone",
      "minY": 1,
      "maxY": 16,
      "maxVeinSize": 7,
      "spawnRate": 0.0,
      "biomeBlacklist": [],
      "biomeWhitelist": []
    }
  ]
}
```

No coal or diamond spawned for me, but the rest of the ores did.
![2021-11-09_22 17 11](https://user-images.githubusercontent.com/5883716/141006541-0e0036b1-e75e-4b19-bd72-31fe92544af8.png)


Minecraft: 1.17.1
Forge: 37.0.104
Java: "16.0.2" 64bit
OS: Windows 10 Pro
Launched through: CurseForge App
Other mods: World Stripper

**Comment by EwyBoy** [comment]
@Flainity @Atlntssplayer @jankornfeld @lynnpye

Hey! Sorry to tag all of you but I believe I have found the cause of the issue.
Its a very technical bug hence why it has taken me so long to be able to fix it. 

The bug is caused in this part of the code:
```java
private static ConfiguredFeature<?, ?> reconstructOre(Block ore, Block filler, int minY, int maxY, float spawnRate, int maxVeinSize) {
        ModLogger.debug("Reconstructing ore: " + ore);
        String registryName = String.format("%s_%s_%d_%d_%f_%d",
                Objects.requireNonNull(ore.getRegistryName()).getPath(),
                Objects.requireNonNull(filler.getRegistryName()).getPath(),
                minY, maxY, spawnRate, maxVeinSize
        );
        return register(
                registryName, reconstructFeature(
                        ore,
                        filler,
                        minY,
                        maxY,
                        spawnRate,
                        maxVeinSize
                )
        );
    }
```

Specifically:
```java
String registryName = String.format("%s_%s_%d_%d_%f_%d",
                Objects.requireNonNull(ore.getRegistryName()).getPath(),
                Objects.requireNonNull(filler.getRegistryName()).getPath(),
                minY, maxY, spawnRate, maxVeinSize
 );
```

Some Java VMs (Java Virtual Machines) fail to format and cast String.format("%s_%s_%d_%d_%f_%d") properly and ends up creating an illegal `ResourceLocation` for each ore entry. This is why this bug was not occurring for me and most other people.

I hope it works now cause this bug has been so time consuming and hear tearing to fix.
This specific bug is also **not** present on Minecraft `1.17.x`. This bug can also occur if you mess up your JSON data files so then its probably your fault. But everything should now work out of the box with a clean install with only OreTweaker and World Stripper installed.  In the coming days I will work on better debugging tools and making it harder for the end users to mess up the JSON files. Gonna work on a system that catches if it is something wrong and don't allow you to create a world until the JSON files are fixed.

The patch can be found here: https://www.curseforge.com/minecraft/mc-mods/ore-tweaker/files/3520897
So make sure you are using version `2.6.+` from now on.
Please tell me if this patch fixes this issue for you and if you still have problems with this issue on a clean install with the patch comment here.

Thank you for your patience and all help with this issue.
