### ISSUE TITLE
Fabric Version for 1.18?

### ISSUE THREAD

**Issue by RoKat6** [EwyBoy/OreTweaker#82]
I wanted to add this mod to a modded server I'm making, but it seems like it only supports Forge. Do you have a Fabric port for 1.18? If not, do you know any other mods like this that are on Fabric?

**Comment by EwyBoy** [comment]
Fabric support is not going to happen. The only reason this mod exist is because Forge has made a ton of nice features for us mod developers that allows us to easily register and hook into world generation. Fabric does not have anything like that and makes it almost impossible for me to develop this kind of tool for Fabric. I also don't think there is any alternatives like this for Fabric for this exact reason. 

Sorry

-Ewy
